# Generated by Django 5.2.1 on 2025-06-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_degree_alter_student_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='official_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
